{% set name = "PTMCMCSampler" %}
{% set version = "1.0.0" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    git_url: https://github.com/jellis18/PTMCMCSampler.git
    # git_rev:
    git_depth: 1

build:
    number: 1

# test:
#     source_files:
#         - tests/
#     commands:
#         # run tests for enterprise here:
#         # or we could make a test.sh script

requirements:
    build:
        - python=3.7

    host:
        - python=3.7
        - defaults::openblas
        - defaults::numpy
        - defaults::scipy >=1.2.0
        - aarondjohnson::acor

    run:
        - python=3.7
        - defaults::openblas
        - defaults::numpy
        - defaults::scipy >=1.2.0
        - aarondjohnson::acor
